apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-front-deployment
  namespace: default
spec:
  selector:
    matchLabels:
       app: web
       tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - name: nginx-front
        image: nginx
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: nginx-front
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-front
        configMap:
          name: nginx-front
          items:
          - key: config
            path: default.conf
