apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-www-servicea
data:
  htmla: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to the greatest place on the earth!</title>
    <style>
      body {
          width: 35em;
          margin: 0 auto;
          font-family: Tahoma, Verdana, Arial, sans-serif;
        }
        </style>
        </head>
        <body>
        <h1>Hello Vitaly! The matrix has you</h1>
        <p>THIS IS SERVICE AAAAAAAAAAA </p>

        <p><em>Thank you for using our services.</em></p>
        </body>
        </html>
