---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-back
data:
  config: |
      server {
          listen       8081;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html/servicea;
            index  serviceA.html index.htm;
          }

          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
            root   /usr/share/nginx/html;
          }
        }

        server {
          listen       8082;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html/serviceb;
            index  serviceB.html index.htm;
          }

          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
            root   /usr/share/nginx/html;
          }
        }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-www-servicea
data:
  htmla: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to the greatest place on the earth!</title>
    <style>
      body {
          width: 35em;
          margin: 0 auto;
          font-family: Tahoma, Verdana, Arial, sans-serif;
        }
        </style>
        </head>
        <body>
        <h1>Hello Vitaly! The matrix has you</h1>
        <p>THIS IS SERVICE AAAAAAAAAAA </p>

        <p><em>Thank you for using our services.</em></p>
        </body>
        </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-www-serviceb
data:
  htmlb: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to the greatest place on the earth!</title>
    <style>
      body {
          width: 35em;
          margin: 0 auto;
          font-family: Tahoma, Verdana, Arial, sans-serif;
        }
        </style>
        </head>
        <body>
        <h1>Hello Vitaly! The matrix has you</h1>
        <p>THIS IS SERVICE BBBBBBBBBBB </p>

        <p><em>Thank you for using our services.</em></p>
        </body>
        </html>
