---
kind: Service
apiVersion: v1
metadata:
  name: servicea
spec:
  selector:
    app: web
    tier: backend
  ports:
  - name: servicea
    protocol: TCP
    port: 8081
    targetPort: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: serviceb
spec:
  selector:
    app: web
    tier: backend
  ports:
  - name: serviceb
    protocol: TCP
    port: 8082
    targetPort: 8082
